spring.application.name=subastar
# Configuración del servidor
server.port=8080
server.servlet.context-path=/v1





spring.datasource.url=jdbc:sqlserver://subastar-servidor.database.windows.net:1433;database=subastardb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=adminSubastar
spring.datasource.password=Subastar123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



cloudinary.cloud-name=dgvj0kcez
cloudinary.api-key=451855175326522
cloudinary.api-secret=iXPzGz0A4hfXVUyVO8duIbivERA



# Configuración JPA (Muestra las consultas en consola y respeta tus tablas manuales)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none